export const techOptions = [
    "Javascript",
    "Typescript",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "ReactJS",
    "NextJS",
    "MongoDB",
    "ExpressJS",
    "NodeJS",
    "Payload CMS",
    "Strapi CMS",
    "Charts",
    "multer",
    "cloudinary",
    "PostgreSQL",
    "SQL",
    "AWS",
    "Vercel",
    "Render",
    "NextAuth",
    "Shadcn UI",
    "Material UI(MUI)",
    "Mongoose"
]
